services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    restart: unless-stopped
    networks:
      - inception
    expose:
      - "3306"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pscala/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/pscala/data/wordpress
      o: bind


networks:
  inception:
    driver: bridge
